<?php
/**
 * Patient-Facing Calendar Interface
 */

define('TERMINKALENDER', true);
require_once 'includes/config.php';
require_once 'includes/db.php';
require_once 'includes/functions.php';

// Start session for CSRF protection
if (session_status() === PHP_SESSION_NONE) {
    session_start();
}

// Clean old appointments (run on every page load, but actual deletion is date-based)
cleanOldAppointments();

$db = Database::getInstance()->getConnection();

// Get all active locations
$stmt = $db->query("SELECT id, name, address FROM wp_terminkalender_locations WHERE is_active = 1 ORDER BY id");
$locations = $stmt->fetchAll();
?>
<!DOCTYPE html>
<html lang="de">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Online Terminbuchung - <?php echo BRAND_NAME; ?></title>
    <link rel="stylesheet" href="assets/css/style.css">
</head>
<body>
    <div class="container">
        <header>
            <div class="header-content">
                <a href="https://winter.wien" class="logo-link" title="Zur Homepage">
                    <img src="Logo_Ordination_Winter-300x296.png" alt="Logo DDr. Fabian Winter" class="header-logo">
                </a>
                <div class="header-text">
                    <h1>Online Terminbuchung</h1>
                    <p class="subtitle"><?php echo BRAND_NAME; ?></p>
                </div>
            </div>
            <div class="homepage-link-container">
                <a href="https://winter.wien" class="homepage-link">← Zur Homepage</a>
            </div>
        </header>

        <main>
            <!-- Location Selection -->
            <div class="location-selector">
                <label for="location-select">Standort wählen:</label>
                <select id="location-select" class="form-control">
                    <option value="">Bitte wählen Sie einen Standort</option>
                    <?php foreach ($locations as $location): ?>
                        <option value="<?php echo $location['id']; ?>">
                            <?php echo htmlspecialchars($location['name']); ?> -
                            <?php echo htmlspecialchars($location['address']); ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>

            <!-- Calendar Container -->
            <div id="calendar-container" style="display: none;">
                <div class="calendar-navigation">
                    <button id="prev-week" class="btn btn-secondary">&larr; Vorherige Woche</button>
                    <h2 id="current-week-display"></h2>
                    <button id="next-week" class="btn btn-secondary">Nächste Woche &rarr;</button>
                </div>

                <div id="calendar-grid" class="calendar-grid">
                    <!-- Calendar will be generated by JavaScript -->
                </div>
            </div>

            <div id="no-location-message" class="info-message">
                Bitte wählen Sie zuerst einen Standort aus.
            </div>
        </main>
    </div>

    <!-- Booking Modal -->
    <div id="booking-modal" class="modal">
        <div class="modal-content">
            <span class="close">&times;</span>
            <h2>Termin buchen</h2>

            <div id="booking-info" class="booking-info">
                <p><strong>Standort:</strong> <span id="modal-location"></span></p>
                <p><strong>Datum:</strong> <span id="modal-date"></span></p>
                <p><strong>Uhrzeit:</strong> <span id="modal-time"></span></p>
                <p><strong>Dauer:</strong> <span id="modal-duration"></span> Minuten</p>
            </div>

            <form id="booking-form">
                <input type="hidden" id="form-location-id" name="location_id">
                <input type="hidden" id="form-date" name="appointment_date">
                <input type="hidden" id="form-time" name="appointment_time">
                <input type="hidden" id="form-duration" name="duration">
                <input type="hidden" name="csrf_token" value="<?php echo generateCSRFToken(); ?>">

                <div class="form-group">
                    <label for="patient-name">Name: *</label>
                    <input type="text" id="patient-name" name="patient_name" required maxlength="100" class="form-control">
                </div>

                <div class="form-group">
                    <label for="patient-phone">Telefonnummer: *</label>
                    <input type="tel" id="patient-phone" name="patient_phone" required maxlength="50" class="form-control" placeholder="z.B. 0664 123 45 67">
                </div>

                <div class="form-group">
                    <label for="patient-comment">Kommentar (optional):</label>
                    <textarea id="patient-comment" name="patient_comment" rows="3" maxlength="500" class="form-control"></textarea>
                </div>

                <div class="form-actions">
                    <button type="button" class="btn btn-secondary" id="cancel-booking">Abbrechen</button>
                    <button type="submit" class="btn btn-primary">Termin bestätigen</button>
                </div>
            </form>

            <div id="booking-success" style="display: none;">
                <div class="success-message">
                    <p>Danke für das Buchen des Termins. Sollten Sie den Termin nicht einhalten können, bitte kontaktieren Sie uns unter ordination@winter.wien oder telefonisch unter 0664 133 15 62.</p>
                    <p style="margin-top: 20px;">
                        <a href="#" id="download-ics" class="btn btn-secondary" style="text-decoration: none;">
                            📅 Kalendereintrag herunterladen
                        </a>
                    </p>
                </div>
                <button class="btn btn-primary" id="close-success">Schließen</button>
            </div>

            <div id="booking-error" style="display: none;">
                <div class="error-message">
                    <p id="error-text"></p>
                </div>
                <button class="btn btn-secondary" id="close-error">Schließen</button>
            </div>
        </div>
    </div>

    <footer>
        <p>&copy; <?php echo date('Y'); ?> <?php echo BRAND_NAME; ?>. Alle Rechte vorbehalten.</p>
    </footer>

    <script src="assets/js/calendar.js?v=4"></script>
</body>
</html>
